name: build and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1  # shallow clone

      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: pwsh

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Configure CMake
        run: >
          cmake -S . -B out
          -DBGUI_USE_OPENGL=OFF
          -DBGUI_USE_OPENGL=OFF
          -DBGUI_USE_VULKAN=OFF
          -DBGUI_USE_GLFW=OFF
          -DBGUI_BUILD_EXAMPLES=OFF
          -DBGUI_USE_FREETYPE=OFF
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake --build out --config Debug

      - name: Build (Windows — paralelo)
        if: runner.os == 'Windows'
        run: cmake --build out --config Debug -- /m

      - name: Run Tests
        run: ctest --test-dir out --output-on-failure -C Debug -V
