name: build and test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1  # shallow clone

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Install libraries (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpng-dev

      - name: Install libraries (macOS)
        if: runner.os == 'macOS'
        run: brew install libpng

      - name: Configure CMake
        run: >
          cmake -S . -B out
          -DBGUI_USE_OPENGL=OFF
          -DBGUI_USE_VULKAN=OFF
          -DBGUI_USE_GLFW=OFF
          -DBGUI_BUILD_EXAMPLES=OFF
          -DBGUI_USE_FREETYPE=OFF
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run: cmake --build out --config Debug --parallel

      - name: Run Tests
        run: ctest --test-dir out --output-on-failure -C Debug -V
